# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

{
  lib,
  config,
  pkgs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ./containers
    ./services
    ./secrets.nix
    ./disko.nix
    ./packages.nix
  ];

  programs.zsh.enable = true;

  nix = {
    gc = {
      automatic = true;
      dates = "daily";
    };
    settings = {
      experimental-features = [
        "nix-command"
        "flakes"
      ];
      download-buffer-size = 500000000; # 500 MB
    };
  };

  services.xserver = {
    enable = true;
    videoDrivers = lib.mkDefault [ "nvidia" ];
  };

  hardware.graphics.enable = true;
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
  hardware.nvidia-container-toolkit.enable = true;

  boot.loader.systemd-boot.enable = true;
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "net.ipv4.ip_forward" = 1;
  };

  networking = {
    hostName = "erebos";
    networkmanager.enable = true;
    firewall = {
      enable = true;
      checkReversePath = "loose";
      allowedTCPPorts = [ 80 443 ];
      trustedInterfaces = [ "podman0" "tailscale0" ];
    };
    enableIPv6 = true;
    nameservers = [
      "9.9.9.9"
      "149.112.112.112"
    ];
    interfaces = {
      enp7s0.wakeOnLan.enable = true;
    };
  };

  time.timeZone = "Europe/Paris";

  users.groups.media = {
    gid = 982;
  };
  users.users.hades = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "libvirtd"
      "video"
      "input"
      "uinput"
      "render"
      "audio"
      "media"
    ];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEeuZsB9sWwgvdaqGH/TDnvk18/Ta+qofcjC29IXQkXk poseidon@pontos"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILAeeNJZnFaAp8AWeq1f/R13J3hr0YTEsfFx9vdcpgtK athena@strategos"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFiTb/R0EMli7oAlf6WFaSj/HR95QkatL8abnhfkoUrI Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEBVW6wKpMU7m35M8k6heZDmDGO1IYWA7r6iaGrlTldB hugo@L-5CD4024FCN"
    ];
  };

  environment.sessionVariables = rec {
    TERM = "xterm-256color";
    EDITOR = "vim";
  };

  systemd.tmpfiles.rules = [
    # "d /data/downloads	0775	${config.services.transmission.user}	${config.services.transmission.group} -"
    "d /data/Series     0775	${config.services.sonarr.user}		    ${config.services.sonarr.group}       -"
    "d /data/Animes     0775 	${config.services.sonarr.user} 		    ${config.services.sonarr.group}       -"
    "d /data/Movies     0775 	${config.services.radarr.user} 		    ${config.services.radarr.group}       -"
  ];

  system.autoUpgrade = {
    enable = true;
    allowReboot = true;
    dates = "Sun 04:00";
    randomizedDelaySec = "30min";
  };
  system.stateVersion = "24.11";
}
