{ inputs, pkgs,... }:

{
  environment.systemPackages = with pkgs; [
    waybar
    hyprpaper
    hypridle
    hyprsunset
    blueman
    vim
    git
    nixd
    nil
    ruff
    basedpyright
    ripgrep
    nerd-fonts.caskaydia-cove
    ghostty
    pamixer
    libnotify
    pavucontrol
    lm_sensors
    networkmanagerapplet
    hyprpaper
    brightnessctl
    hyprpolkitagent
    nautilus
    jq
    wlogout
    btop
    hyprshot
    envsubst
    delfin
    fastfetch
    spotify
    discord
    inputs.zen-browser.packages."${pkgs.system}".default
    obsidian
    hyprlock
    filezilla
    lshw
    eog
    unrar
    tmux
    unzip
    tor-browser
    nvtopPackages.full
    proton-vpn
    irssi
    usbutils
    mangohud
    deluge
    wget
    qemu_kvm
    qemu-user
    virt-manager
    killall
    vscode
    gparted
    popsicle
    bitwarden-desktop
    nsz
    prismlauncher
    nwg-displays
    fw-ectool
    ryzenadj
    system-config-printer
    clinfo
    net-tools
    signal-desktop
    jellyfin-media-player
    moonlight-qt
    neocmakelsp
    bc
    arduino-ide
    podman-compose
    feishin
    obs-studio
    qt6.qtwayland
    (element-desktop.override {
      commandLineArgs = "--password-store=gnome-libsecret";
    })
    protonup-ng
    heroic
    pciutils
    inputs.kiln.packages.${pkgs.system}.default
    cinny-desktop
    audacity
    seahorse
    bruno
    rustup
    clang
    nodejs
    nextcloud-client
    playerctl
    wofi
    (pkgs.catppuccin-sddm.override {
      flavor = "mocha";
      accent = "mauve";
    })
    dex
    linux-firmware
    mpv
    inputs.quickconf.packages.${pkgs.system}.default
    gns3-server
    gns3-gui
    lmstudio
    podman-desktop
    wireshark
    flowblade
    ghidra
  ];
}
