{ inputs, pkgs,... }:

{
  environment.systemPackages = with pkgs; [
    vim
    git
    nixd
    nil
    ruff
    basedpyright
    fastfetch
    ripgrep
    nerd-fonts.caskaydia-cove
    ghostty
    pamixer
    libnotify
    pavucontrol
    lm_sensors
    networkmanagerapplet
    hyprpaper
    brightnessctl
    hyprpolkitagent
    nautilus
    jq
    wlogout
    btop
    hyprshot
    envsubst
    delfin
    fastfetch
    spotify
    discord
    inputs.zen-browser.packages."${system}".default
    nextcloud-client
    obsidian
    hyprlock
    filezilla
    lshw
    vlc
    eog
    unrar
    tmux
    unzip
    tor-browser
    nvtopPackages.full
    protonvpn-gui
    pulseaudio
    irssi
    usbutils
    mangohud
    deluge
    wget
    qemu_kvm
    qemu-user
    virt-manager
    killall
    vscode
    gparted
    popsicle
    bitwarden-desktop
    nsz
    prismlauncher
    nwg-displays
    fw-ectool
    ryzenadj
    system-config-printer
    clinfo
    net-tools
    signal-desktop
    jellyfin-media-player
    moonlight-qt
    inputs.eden-emulator.packages.${pkgs.system}.default
    neocmakelsp
    bc
    arduino-ide
    podman-compose
  ];
}
