{ ... }:

let
  eth = "enu1u1u1";
	# wifi = "wlu1u3";
  wifi = "wlan0";
in
{
  services.create_ap = {
    enable = true;
    settings = {
      INTERNET_IFACE = "${eth}";
      WIFI_IFACE = "${wifi}";
      SSID = "Chambre Hugo";
      PASSPHRASE = "12345678";
    };
  };
  systemd.services.create_ap = {
    # This unit is automatically generated by systemd when the network device appears
    after = [ "sys-subsystem-net-devices-${eth}.device" ];
    wants = [ "sys-subsystem-net-devices-${eth}.device" ];
  };
}
