{ inputs, pkgs,... }:

{
  environment.systemPackages = with pkgs; [
    vim
    git
    nixd
    nil
    ruff
    basedpyright
    fastfetch
    ripgrep
    nerd-fonts.caskaydia-cove
    ghostty
    pamixer
    libnotify
    pavucontrol
    lm_sensors
    networkmanagerapplet
    hyprpaper
    brightnessctl
    hyprpolkitagent
    nautilus
    jq
    wlogout
    btop
    hyprshot
    envsubst
    delfin
    fastfetch
    spotify
    inputs.zen-browser.packages."${system}".default
    nextcloud-client
    obsidian
    hyprlock
    filezilla
    lshw
    vlc
    eog
    unrar
    tmux
    unzip
    tor-browser
    nvtopPackages.full
    protonvpn-gui
    pulseaudio
    irssi
    usbutils
    mangohud
    deluge
    asm-lsp
    clang-tools
    package-version-server
    wget
    qemu
    virt-manager
    killall
    vscode
    gparted
    popsicle
    heroic
    bitwarden-desktop
    nsz
    prismlauncher
    tor-browser
    fw-ectool
    fw-fanctrl
    discord
    openjdk
    wineWowPackages.stableFull
    mesa-demos
    radeontop
    pciutils
    rocmPackages.clr
    rocmPackages.clr.icd
    rocmPackages.rocminfo
    rocmPackages.rocm-core
    usbutils
    exfat
    nwg-displays
  ];
}
